name: ReportWebhook
main: com.example.reportwebhook.ReportWebhookPlugin
version: 1.0.1
api-version: '1.20'
author: chatgpt
commands:
  report:
    description: Report a player to staff via webhook
    usage: /report <player> <reason>
    permission: reportwebhook.use
permissions:
  reportwebhook.use:
    description: Allows using /report
    default: true
